#!/bin/bash
dexpath=$1
cmd_param='{"action":"baksmali","dexpath":"'
cmd_param+=${dexpath}
cmd_param+='"}'
echo $cmd_param
adb shell am broadcast -a com.zjdroid.invoke --ei target $1 --es cmd $cmd_param
